# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.26
# 

Name:       mapplauncherd

# >> macros
# << macros

Summary:    Application launcher for fast startup
Version:    4.1.0
Release:    1
Group:      System/Daemons
License:    LGPLv2+
URL:        https://github.com/nemomobile/mapplauncherd/
Source0:    %{name}-%{version}.tar.bz2
Source100:  mapplauncherd.yaml
Requires:   systemd-user-session-targets
Requires(post): /sbin/ldconfig
Requires(postun): /sbin/ldconfig
BuildRequires:  pkgconfig(x11)
BuildRequires:  pkgconfig(xtst)
BuildRequires:  pkgconfig(xextproto)
BuildRequires:  pkgconfig(xi)
BuildRequires:  pkgconfig(xext)
BuildRequires:  pkgconfig(systemd)
BuildRequires:  pkgconfig(QtCore)
BuildRequires:  pkgconfig(QtTest)
BuildRequires:  pkgconfig(dbus-1)
BuildRequires:  cmake
BuildRequires:  python
Provides:   meegotouch-applauncherd > 3.0.3
Obsoletes:   meegotouch-applauncherd <= 3.0.3

%description
Application invoker and launcher daemon that speed up
application startup time and share memory. Provides also
functionality to launch applications as single instances.


%package devel
Summary:    Development files for launchable applications
Group:      Development/Tools
Requires:   %{name} = %{version}-%{release}
Provides:   meegotouch-applauncherd-devel > 3.0.3
Obsoletes:  meegotouch-applauncherd-devel <= 3.0.3

%description devel
Development files for creating applications that can be launched
using mapplauncherd.


%prep
%setup -q -n %{name}-%{version}

# >> setup
# << setup

%build
# >> build pre
export BUILD_TESTS=1
export MEEGO=1
unset LD_AS_NEEDED
# << build pre

%configure --disable-static
make %{?jobs:-j%jobs}

# >> build post
# << build post

%install
rm -rf %{buildroot}
# >> install pre
# << install pre
%make_install

# >> install post

# Don't use %exclude, remove at install phase
rm -f %{buildroot}/usr/share/fala_images/fala_qml_helloworld

mkdir -p %{buildroot}/usr/lib/systemd/user/user-session.target.wants || true
ln -s ../booster-generic.service %{buildroot}/usr/lib/systemd/user/user-session.target.wants/
# << install post

%post -p /sbin/ldconfig

%postun -p /sbin/ldconfig

%files
%defattr(-,root,root,-)
%{_bindir}/invoker
%{_bindir}/single-instance
%{_libdir}/libapplauncherd.so*
%{_libexecdir}/mapplauncherd/booster-generic
%{_libdir}/systemd/user/booster-generic.service
%{_libdir}/systemd/user/user-session.target.wants/booster-generic.service
# >> files
# << files

%files devel
%defattr(-,root,root,-)
%{_includedir}/applauncherd/*
# >> files devel
# << files devel
