# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.25
# 

Name:       mapplauncherd

# >> macros
# << macros

Summary:    Application launcher for fast startup
Version:    4.0.1
Release:    1
Group:      System/Daemons
License:    LGPLv2+
URL:        https://github.com/nemomobile/mapplauncherd/
Source0:    %{name}-%{version}.tar.bz2
Source1:    mapplauncherd.service
Source100:  mapplauncherd.yaml
Requires(post): /sbin/ldconfig
Requires(postun): /sbin/ldconfig
BuildRequires:  pkgconfig(x11)
BuildRequires:  pkgconfig(xtst)
BuildRequires:  pkgconfig(xextproto)
BuildRequires:  pkgconfig(xi)
BuildRequires:  pkgconfig(xext)
BuildRequires:  pkgconfig(systemd)
BuildRequires:  pkgconfig(QtCore)
BuildRequires:  pkgconfig(QtTest)
BuildRequires:  cmake
BuildRequires:  python
Provides:   meegotouch-applauncherd > 3.0.3
Obsoletes:   meegotouch-applauncherd <= 3.0.3

%description
Application invoker and launcher daemon that speed up
application startup time and share memory. Provides also
functionality to launch applications as single instances.


%package devel
Summary:    Development files for launchable applications
Group:      Development/Tools
Requires:   %{name} = %{version}-%{release}
Provides:   meegotouch-applauncherd-devel > 3.0.3
Obsoletes:   meegotouch-applauncherd-devel <= 3.0.3

%description devel
Development files for creating applications that can be launched
using mapplauncherd.


%package testapps
Summary:    Test applications for launchable applications
Group:      Development/Tools
Requires:   %{name} = %{version}-%{release}

%description testapps
Test applications used for testing mapplauncherd.


%package tests
Summary:    Test scripts for launchable applications
Group:      Development/Tools
Requires:   %{name} = %{version}-%{release}
Requires:   %{name}-testapps = %{version}-%{release}

%description tests
Test scripts used for testing meegotouch-applauncherd.



%prep
%setup -q -n %{name}-%{version}

# >> setup
# << setup

%build
# >> build pre
export BUILD_TESTS=1
export MEEGO=1
unset LD_AS_NEEDED
# << build pre

%configure --disable-static
make %{?jobs:-j%jobs}

# >> build post
# << build post

%install
rm -rf %{buildroot}
# >> install pre
# << install pre
%make_install
mkdir -p %{buildroot}%{_libdir}/systemd/user/
cp -a %{SOURCE1} %{buildroot}%{_libdir}/systemd/user/


# >> install post
(cd %{buildroot}%{_libdir}/systemd/user; ln -s mapplauncherd.service meegotouch-applauncherd.service)

# rpmlint complains about installing binaries in /usr/share, so
# move them elsewhere and leave a symlink in place.
mv %{buildroot}/usr/share/applauncherd-tests %{buildroot}/usr/lib
(cd %{buildroot}/usr/share; ln -s ../lib/applauncherd-tests)
# Don't use %exclude, remove at install phase
rm -f %{buildroot}/usr/share/fala_images/fala_qml_helloworld
# << install post


%post -p /sbin/ldconfig

%postun -p /sbin/ldconfig

%files
%defattr(-,root,root,-)
%{_bindir}/invoker
%{_libdir}/libapplauncherd.so*
%{_libdir}/applauncherd/libebooster.so
%{_bindir}/applauncherd.bin
%{_bindir}/applauncherd
%{_bindir}/single-instance
%{_libdir}/systemd/user/mapplauncherd.service
%{_libdir}/systemd/user/meegotouch-applauncherd.service
# >> files
# << files

%files devel
%defattr(-,root,root,-)
%{_includedir}/applauncherd/*
# >> files devel
# << files devel

%files testapps
%defattr(-,root,root,-)
%{_bindir}/fala_gettime_ms
%{_bindir}/fala_pixelchanged
%{_bindir}/fala_status
%{_bindir}/fala_gettime
%{_bindir}/fala_windowid
%{_bindir}/fala_wait
# >> files testapps
# << files testapps

%files tests
%defattr(-,root,root,-)
%{_datadir}/applauncherd-M-art-tests/tests.xml
%{_datadir}/applauncherd-M-bug-tests/tests.xml
%{_datadir}/applauncherd-M-functional-tests/tests.xml
%{_datadir}/applauncherd-M-performance-tests/tests.xml
%{_datadir}/applauncherd-tests
%{_libdir}/applauncherd-tests/tests.xml
%{_libdir}/applauncherd-tests/ut_booster
%{_libdir}/applauncherd-tests/ut_daemon
%{_libdir}/applauncherd-tests/ut_ebooster
%{_libdir}/applauncherd-tests/ut_connection
%{_libdir}/applauncherd-tests/ut_socketmanager
%{_libdir}/applauncherd-tests/libutplugin.so
%{_libdir}/applauncherd-tests/libutwithcreate.so
%{_libdir}/applauncherd-tests/libutwithcreatetype.so
%{_libdir}/applauncherd-tests/libutwithcreatetypesocketname.so
%{_libdir}/applauncherd-tests/libutwithlock.so
%{_libdir}/applauncherd-tests/libutwithlockunlock.so
%{_libdir}/applauncherd-tests/ut_appdata
%{_libdir}/applauncherd-tests/ut_boosterpluginregistry
%{_libdir}/applauncherd-tests/ut_logger
%{_libdir}/applauncherd-tests/ut_singleinstance
%{_datadir}/applauncherd-M-testscripts/check_pipes.py
%{_datadir}/applauncherd-M-testscripts/check_pipes.pyc
%{_datadir}/applauncherd-M-testscripts/check_pipes.pyo
%{_datadir}/applauncherd-M-testscripts/signal-forward/fala_sf_m.py
%{_datadir}/applauncherd-M-testscripts/signal-forward/fala_sf_m.pyc
%{_datadir}/applauncherd-M-testscripts/signal-forward/fala_sf_m.pyo
%{_datadir}/applauncherd-M-testscripts/signal-forward/fala_sf_m.sh
%{_datadir}/applauncherd-M-testscripts/signal-forward/fala_sf_qt.py
%{_datadir}/applauncherd-M-testscripts/signal-forward/fala_sf_qt.pyc
%{_datadir}/applauncherd-M-testscripts/signal-forward/fala_sf_qt.pyo
%{_datadir}/applauncherd-M-testscripts/signal-forward/fala_sf_qt.sh
%{_datadir}/applauncherd-M-testscripts/tc_theming.rb
%{_datadir}/applauncherd-M-testscripts/test-func-launcher.py
%{_datadir}/applauncherd-M-testscripts/test-func-launcher.pyc
%{_datadir}/applauncherd-M-testscripts/test-func-launcher.pyo
%{_datadir}/applauncherd-M-testscripts/ts_prestartapp.rb
%{_datadir}/applauncherd-M-testscripts/fala_wid
%{_datadir}/applauncherd-M-testscripts/fala_xres_wl
%{_datadir}/applauncherd-M-testscripts/fala_xres_wol
%{_datadir}/applauncherd-M-testscripts/test-perf.rb
%{_datadir}/applauncherd-M-testscripts/utils.py
%{_datadir}/applauncherd-M-testscripts/utils.pyc
%{_datadir}/applauncherd-M-testscripts/utils.pyo
# >> files tests
# << files tests
