#!/bin/sh

# Use 50 chars long dummy parameter to reserve place for application
# name and parameters so that we get some space to modify the argument
# list seen in /proc/[PID]/cmdline. 
# If the length of the application name with parameters is longer than space 
# available, parameters will be cut off. The main function will still always
# get the complete argument list.
exec /usr/bin/applauncherd.bin "                                                  "

