# 
# Do not Edit! Generated by:
# spectacle version 0.18
# 
# >> macros
# << macros

Name:       meegotouch-applauncherd
Summary:    Application launcher for fast startup
Version:    0.12.1
Release:    1
Group:      System/Daemons
License:    LGPLv2+
URL:        http://meego.gitorious.com/meegotouch/meegotouch-applauncherd
Source0:    %{name}-%{version}.tar.bz2
Source100:  meegotouch-applauncherd.yaml
Patch0:     0001-Changes-use-usr-bin-ruby-instead-of-usr-bin-ruby1.8-.patch
Patch1:     0002-Changes-In-MeeGo-install-file-etc-xdg-autostart-appl.patch
BuildRequires:  pkgconfig(QtCore)
BuildRequires:  pkgconfig(meegotouch)
BuildRequires:  cmake


%description
Application invoker and launcher daemon that speed up
application startup time.



%package devel
Summary:    Development files for launchable applications
Group:      Development/Tools
Requires:   %{name} = %{version}-%{release}

%description devel
Development files for creating applications that can be launched 
using meegotouch-applauncherd.


%package testapps
Summary:    Test applications for launchable applications
Group:      Development/Tools
Requires:   %{name} = %{version}-%{release}

%description testapps
Test applications used for testing meegotouch-applauncherd.


%package tests
Summary:    Test scripts for launchable applications
Group:      Development/Tools
Requires:   %{name} = %{version}-%{release}
Requires:   %{name}-testapps = %{version}-%{release}

%description tests
Test scripts used for testing meegotouch-applauncherd.



%prep
%setup -q -n %{name}-%{version}

# 0001-Changes-use-usr-bin-ruby-instead-of-usr-bin-ruby1.8-.patch
%patch0 -p1
# 0002-Changes-In-MeeGo-install-file-etc-xdg-autostart-appl.patch
%patch1 -p1
# >> setup
# << setup

%build
# >> build pre
export BUILD_TESTS=1
export MEEGO=1
# << build pre

%configure --disable-static
make %{?jobs:-j%jobs}

# >> build post
# << build post
%install
rm -rf %{buildroot}
# >> install pre
# << install pre
%make_install 

# >> install post
# rpmlint complains about installing binaries in /usr/share, so
# move them elsewhere and leave a symlink in place.
mv %{buildroot}/usr/share/applauncherd-tests %{buildroot}/usr/lib
(cd %{buildroot}/usr/share; ln -s ../lib/applauncherd-tests)
# << install post















%files
%defattr(-,root,root,-)
%{_bindir}/invoker
%{_bindir}/applauncherd.bin
%{_bindir}/applauncherd
%config %{_sysconfdir}/xdg/autostart/applauncherd.desktop
# >> files
# << files


%files devel
%defattr(-,root,root,-)
%{_libdir}/pkgconfig/meegotouch-boostable.pc
%doc %{_docdir}/applauncherd/README
%{_datadir}/qt4/mkspecs/features/meegotouch-boostable.prf
# >> files devel
# << files devel

%files testapps
%defattr(-,root,root,-)
%{_bindir}/fala_ft_hello
%{_bindir}/fala_status.launch
%{_bindir}/fala_ft_hello1
%{_bindir}/fala_ft_hello2
%{_bindir}/fala_ft_hello.launch
%{_bindir}/fala_ft_hello1.launch
%{_bindir}/fala_ft_hello2.launch
%{_bindir}/fala_ft_creds1
%{_bindir}/fala_ft_creds1.launch
%{_bindir}/fala_ft_creds2
%{_bindir}/fala_ft_creds2.launch
%{_bindir}/fala_testapp
%{_bindir}/fala_ft_themetest.launch
%{_bindir}/fala_ft_themetest
%{_datadir}/themes/base/meegotouch/fala_ft_themetest/svg/baa.svg
%{_datadir}/dbus-1/services/com.nokia.fala_testapp.service
# >> files testapps
# << files testapps

%files tests
%defattr(-,root,root,-)
%{_datadir}/applauncherd-art-tests/tests.xml
%{_datadir}/applauncherd-bug-tests/tests.xml
%{_datadir}/applauncherd-functional-tests/tests.xml
%{_datadir}/applauncherd-performance-tests/tests.xml
%{_datadir}/applauncherd-tests
%{_libdir}/applauncherd-tests/tests.xml
%{_libdir}/applauncherd-tests/ut_booster
%{_libdir}/applauncherd-tests/ut_connection
%{_libdir}/applauncherd-tests/ut_daemon
%{_libdir}/applauncherd-tests/ut_mbooster
%{_libdir}/applauncherd-tests/ut_qtbooster
%{_datadir}/applauncherd-testscripts/check_pipes.py
%{_datadir}/applauncherd-testscripts/check_pipes.pyc
%{_datadir}/applauncherd-testscripts/check_pipes.pyo
%{_datadir}/applauncherd-testscripts/fala_sf.py
%{_datadir}/applauncherd-testscripts/fala_sf.pyc
%{_datadir}/applauncherd-testscripts/fala_sf.pyo
%{_datadir}/applauncherd-testscripts/fala_sf.sh
%{_datadir}/applauncherd-testscripts/tc_theming.rb
%{_datadir}/applauncherd-testscripts/test-func-launcher.py
%{_datadir}/applauncherd-testscripts/test-func-launcher.pyc
%{_datadir}/applauncherd-testscripts/test-func-launcher.pyo
%{_datadir}/applauncherd-testscripts/test-perf-mbooster.py
%{_datadir}/applauncherd-testscripts/test-perf-mbooster.pyc
%{_datadir}/applauncherd-testscripts/test-perf-mbooster.pyo
%{_datadir}/applauncherd-testscripts/ts_prestartapp.rb
%{_datadir}/themes/base/meegotouch/fala_ft_themetest/style/fala_ft_themetest.css
# >> files tests
# << files tests

