.\" (C) Copyright 2021 justforlxz <zhangdingyuan@uniontech.com>,
.\"
.TH "deepin-turbo" "1" "2021-4-1" "Deepin"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .type         set launch type
.\" for manpage-specific macros, see man(7)
.SH NAME
deepin-turbo \- package manager for deepin.
.SH DESCRIPTION
Package deepin-turbo
.SH OPTIONS
.TP
.B \-h <help>
Displays this help.
.TP
.B \-v <version>
Displays version information
.PP
This manual page was written by
.MT zhangdingyuan@uniontech.com
.ME
for the Debian Project (but may be used by others)