######################################################################
# Automatically generated by qmake (2.01a) Wed Apr 21 10:44:49 2010
######################################################################

TEMPLATE = app
QMAKE_CXXFLAGS += -fPIC -fvisibility=hidden -fvisibility-inlines-hidden
QMAKE_LFLAGS += -pie -rdynamic
TARGET = testapp
DEPENDPATH += .
INCLUDEPATH += .
CONFIG += meegotouch

# Input
SOURCES += main.cpp
